"""primeiro commit

Revision ID: c15c4aba9907
Revises: 
Create Date: 2026-09-28 20:47:45.083265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15c4aba9907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categorias_nome'), ['nome'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_nome'), ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuarios_nome'), type_='unique')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categorias_nome'), type_='unique')

    # ### end Alembic commands ###
